import asyncio
from logging.config import fileConfig
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from alembic import context

from app.database import Base
from app.models.models import Battery, Event  # noqa: F401 — ensure models are registered

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _get_url() -> str:
    """Return the database URL that should be used for migrations.

    Always prefer the URL generated by the application settings.  The value in
    ``alembic.ini`` is a fallback that exists solely for people running
    ``alembic`` manually outside of Docker; it must *never* override whatever
    the environment supplies in our containers.  Using ``settings`` also
    ensures that the same credentials/hostname the API will later use are the
    ones migrations connect with.
    """
    from app.config import settings

    # ``Settings`` provides a default, but when running in Docker we expect an
    # explicit ``DATABASE_URL`` override to be present.  If for some reason
    # neither source yields a usable URL we fall back to the ini value so that
    # local developers still have something to work with.
    url = settings.database_url
    if not url:
        url = config.get_main_option("sqlalchemy.url")
    return url


def run_migrations_offline() -> None:
    url = _get_url()
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True)
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    # make sure the configuration reflects the active settings URL, which is
    # either read from the environment or defined in ``alembic.ini`` as a
    # fallback.  ``run_async_migrations`` itself uses
    # ``config.get_section(...)["sqlalchemy.url"]`` so we have to set the
    # option here before that function is called.
    config.set_main_option("sqlalchemy.url", _get_url())
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
